# Generated by Django 5.2.5 on 2025-11-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(help_text='Professional title', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='About me description')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('video_resume', models.URLField(blank=True, help_text='YouTube link to video resume')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('available', 'Available for Work'), ('busy', 'Busy'), ('not-looking', 'Not Looking')], default='available', max_length=20)),
                ('work_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('flexible', 'Flexible')], default='remote', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('open_to_opportunities', models.BooleanField(default=True)),
                ('available_for_freelance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
