# Generated by Django 5.2.5 on 2025-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3b82f6', help_text="Hex color code (e.g., '#3b82f6')", max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-folder', help_text="FontAwesome icon class (e.g., 'fas fa-globe')", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
