# Generated by Django 5.2.5 on 2025-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_category_color_category_description_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('project', 'Project'), ('skill', 'Skill'), ('achievement', 'Achievement'), ('experience', 'Experience')], default='project', help_text='Type of category (Project, Skill, Achievement, or Experience)', max_length=20),
        ),
    ]
