# Generated by Django 5.2.5 on 2025-11-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_category_options_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentation',
            field=models.TextField(blank=True, help_text='Project documentation in HTML format'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, help_text='Display name for the project', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Project thumbnail image', null=True, upload_to='projects/thumbnails/'),
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
