# Generated by Django 5.2.5 on 2025-11-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_documentation_project_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
    ]
