# Generated by Django 5.2.5 on 2025-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_url',
            field=models.URLField(blank=True, help_text='Other project link', null=True),
        ),
    ]
