# Generated by Django 5.2.5 on 2025-11-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_other_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
