# Generated by Django 5.2.5 on 2025-11-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Job title/position', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time Employment'), ('part-time', 'Part-time'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship'), ('volunteer', 'Volunteer')], default='full-time', help_text='Type of employment', max_length=20)),
                ('employment_status', models.CharField(choices=[('current', 'Current'), ('past', 'Past')], default='current', help_text='Current or past employment', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Work location or Remote', max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_about', models.TextField(blank=True, help_text='Brief company description')),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='experience/logos/')),
                ('start_date', models.DateField(help_text='Employment start date')),
                ('end_date', models.DateField(blank=True, help_text='Employment end date (blank if current)', null=True)),
                ('currently_working', models.BooleanField(default=False, help_text='Currently working here')),
                ('short_description', models.TextField(help_text='Brief summary of role and responsibilities')),
                ('detailed_description', models.TextField(blank=True, help_text='Detailed experience description in HTML format')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('is_draft', models.BooleanField(default=False, help_text='Draft status')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experience/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
