# Generated by Django 5.2.5 on 2025-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_experience_experienceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name (e.g., Python, React)', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Proficiency level', max_length=20)),
                ('proficiency', models.IntegerField(default=50, help_text='Proficiency percentage (0-100)')),
                ('description', models.TextField(blank=True, help_text='Brief description of skill and experience')),
                ('icon_type', models.CharField(choices=[('upload', 'Uploaded Icon'), ('fontawesome', 'FontAwesome Icon')], default='upload', help_text='Type of icon (uploaded image or FontAwesome class)', max_length=20)),
                ('icon_image', models.ImageField(blank=True, help_text='Uploaded skill icon', null=True, upload_to='skills/icons/')),
                ('icon_class', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fab fa-react')", max_length=100)),
                ('certificate_type', models.CharField(blank=True, choices=[('file', 'Certificate File'), ('link', 'Certificate Link')], default='file', help_text='Type of certificate', max_length=20)),
                ('certificate_file', models.FileField(blank=True, help_text='Certificate file (PDF or image)', null=True, upload_to='skills/certificates/')),
                ('certificate_url', models.URLField(blank=True, help_text='Certificate URL link', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('is_draft', models.BooleanField(default=False, help_text='Draft status')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-proficiency', 'name'],
            },
        ),
    ]
