# Generated by Django 5.2.5 on 2025-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Achievement title', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('certification', 'Certification'), ('award', 'Award'), ('competition', 'Competition'), ('recognition', 'Recognition'), ('publication', 'Publication'), ('patent', 'Patent')], help_text='Achievement category', max_length=50)),
                ('issuing_organization', models.CharField(help_text='Organization that issued the achievement', max_length=255)),
                ('achievement_date', models.DateField(help_text='Date achievement was received')),
                ('expiration_date', models.DateField(blank=True, help_text='Expiration date if applicable', null=True)),
                ('no_expiration', models.BooleanField(default=True, help_text="Check if achievement doesn't expire")),
                ('short_description', models.TextField(help_text='Brief description')),
                ('full_description', models.TextField(blank=True, help_text='Detailed description (supports HTML)', null=True)),
                ('icon_type', models.CharField(choices=[('upload', 'Upload Image'), ('fontawesome', 'Font Awesome Icon')], default='upload', help_text='Icon type', max_length=20)),
                ('icon_image', models.ImageField(blank=True, help_text='Upload icon/badge image', null=True, upload_to='achievements/icons/')),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-trophy)', max_length=100, null=True)),
                ('credential_type', models.CharField(choices=[('file', 'Upload File'), ('link', 'URL Link')], default='file', help_text='Credential type', max_length=20)),
                ('credential_file', models.FileField(blank=True, help_text='Upload credential document', null=True, upload_to='achievements/credentials/')),
                ('credential_url', models.URLField(blank=True, help_text='Credential verification URL', max_length=500, null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Credential ID', max_length=255, null=True)),
                ('related_link', models.URLField(blank=True, help_text='Related link', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('is_draft', models.BooleanField(default=False, help_text='Draft status')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-achievement_date', 'title'],
            },
        ),
    ]
