# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


def migrate_categories_to_fk(apps, schema_editor):
    """Migrate old category CharField data to new ForeignKey"""
    Achievement = apps.get_model('portfolio', 'Achievement')
    Category = apps.get_model('portfolio', 'Category')
    
    # Map old category values to new Category objects
    category_mapping = {
        'certification': 'Certification',
        'award': 'Award',
        'competition': 'Competition',
        'recognition': 'Recognition',
        'publication': 'Publication',
        'patent': 'Patent',
    }
    
    for achievement in Achievement.objects.all():
        old_category = achievement.category_old
        if old_category in category_mapping:
            # Try to find or create the corresponding Category
            category, created = Category.objects.get_or_create(
                name=category_mapping[old_category],
                category_type='achievement',
                defaults={
                    'slug': old_category,
                    'icon': 'fas fa-trophy',
                    'color': '#3b82f6'
                }
            )
            achievement.category_new = category
            achievement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_notification'),
    ]

    operations = [
        # Step 1: Rename old category field
        migrations.RenameField(
            model_name='achievement',
            old_name='category',
            new_name='category_old',
        ),
        # Step 2: Add new ForeignKey field
        migrations.AddField(
            model_name='achievement',
            name='category_new',
            field=models.ForeignKey(
                help_text='Achievement category',
                limit_choices_to={'category_type': 'achievement'},
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='achievements_new',
                to='portfolio.category'
            ),
        ),
        # Step 3: Migrate data
        migrations.RunPython(migrate_categories_to_fk, migrations.RunPython.noop),
        # Step 4: Remove old field
        migrations.RemoveField(
            model_name='achievement',
            name='category_old',
        ),
        # Step 5: Rename new field to category
        migrations.RenameField(
            model_name='achievement',
            old_name='category_new',
            new_name='category',
        ),
        # Step 6: Remove icon-related fields
        migrations.RemoveField(
            model_name='achievement',
            name='icon_type',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='icon_class',
        ),
    ]
