# Generated by Django 5.2.12 on 2026-03-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_update_achievement_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.ForeignKey(help_text='Achievement category', limit_choices_to={'category_type': 'achievement'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='portfolio.category'),
        ),
    ]
