# Generated by Django 5.2.12 on 2026-03-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_achievement_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
