# Generated by Django 5.2.12 on 2026-03-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_contactmessage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['created_at'], name='portfolio_c_created_dada1c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email', 'created_at'], name='portfolio_c_email_5fb403_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['ip_address', 'created_at'], name='portfolio_c_ip_addr_f72c70_idx'),
        ),
    ]
