# Generated by Django 5.2.12 on 2026-04-09 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_contactmessage_portfolio_c_created_dada1c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Experience category', limit_choices_to={'category_type': 'experience'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='portfolio.category'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Skill category', limit_choices_to={'category_type': 'skill'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=50, help_text='Proficiency percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
