# Generated by Django 5.2.12 on 2026-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_experience_category_skill_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['is_active', 'is_draft', 'achievement_date', 'created_at'], name='portfolio_a_is_acti_6559dc_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['category', 'is_active', 'is_draft'], name='portfolio_a_categor_b1d4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type', 'name'], name='portfolio_c_categor_b5e67d_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['is_active', 'is_draft', 'order', 'start_date'], name='portfolio_e_is_acti_74323c_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['employment_type', 'is_active', 'is_draft'], name='portfolio_e_employm_f05187_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category', 'is_active', 'is_draft'], name='portfolio_e_categor_ce6007_idx'),
        ),
        migrations.AddIndex(
            model_name='experienceimage',
            index=models.Index(fields=['experience', 'order'], name='portfolio_e_experie_1e72d9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'status', 'order', 'created_at'], name='portfolio_p_is_acti_18f73e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured', 'is_active', 'status'], name='portfolio_p_is_feat_573784_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'is_active', 'status'], name='portfolio_p_categor_b90e85_idx'),
        ),
        migrations.AddIndex(
            model_name='projectscreenshot',
            index=models.Index(fields=['project', 'order'], name='portfolio_p_project_5332e6_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_active', 'is_draft', 'proficiency', 'name'], name='portfolio_s_is_acti_ddc1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['skill_level', 'is_active', 'is_draft'], name='portfolio_s_skill_l_48b75c_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'is_active', 'is_draft'], name='portfolio_s_categor_223b29_idx'),
        ),
    ]
